### ISSUE TITLE
🚧Remove solution items

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#101]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the 2 solutions items shown in the screenshot below.
This will require opening Visual Studio (Not Visual Studio Code).  Just right-click the items in the solution explorer and hit delete.
Make sure to save all or the solution file will not save the changes and git will not pick up those changes.

**Screenshot:**
![image](https://user-images.githubusercontent.com/85414302/235301398-826a822f-cab3-46e6-b059-bf527a1a2ed1.png)

### Acceptance Criteria

- [ ] Solution items removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
