### ISSUE TITLE
🚧Create sonar scan status check workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#103]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a workflow to run as a status check for doing sonar cloud scans.

This is the service to scan code for all kinds of issues, style, security, and quality type issues.
This workflow will run for every change to a PR and also fail or pass the PR for merging based on the scan results.

You can get this workflow from the Velaptor project.  It is rather complicated and was taken from an example from the sonar cloud documentation.

Go [here](https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/.github/workflows/sonar-scan-pr-status-check.yml) to view the workflow in Velaptor.

### Acceptance Criteria

- [x] Sonar scan workflow created
  - [x] The name of the workflow should be _**sonar-scan-pr-status-check.yml**_

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
