### ISSUE TITLE
🚧Improve readme

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#126]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the **_README.md_** file so it renders property in nuget.org.

Do the following:

1. Add 2 spaces to the very end of the first Twitter link at the bottom of the file.
    > **Note** This is to force the second Twitter link to be rendered below the first link
    ```diff
    - [![twitter-logo](https://raw.githubusercontent.com/KinsonDigital/.github/master/Images/twitter-logo-16x16.svg)Calvin Wilkinson](https://twitter.com/KDCoder) (KinsonDigital GitHub Organization - Owner)
    + [![twitter-logo](https://raw.githubusercontent.com/KinsonDigital/.github/master/Images/twitter-logo-16x16.svg)Calvin Wilkinson](https://twitter.com/KDCoder) (KinsonDigital GitHub Organization - Owner)  
    
    [![twitter-logo](https://raw.githubusercontent.com/KinsonDigital/.github/master/Images/twitter-logo-16x16.svg)Kristen Wilkinson](https://twitter.com/kswilky) (KinsonDigital GitHub Organization - Documentation Maintainer & Tester)
    ```
2. Add an extra empty above the last tip code block located in the **🙏🏻 Contributing 🙏🏻** section
    ```md
     👉🏻Add the empty line here👈🏻
    > **💡TIP💡** Most of the time . . 
    ```
3. Add an extra empty line above the bolded **Benefits:** list in the _**✨ Features & Benefits ✨**_ section
    ```md
     👉🏻Add the empty line here👈🏻
    **Benefits:**
    - Increases decoupling
    - Increases testability
    ```

Improve the _**release.yml**_ workflow

### Acceptance Criteria

- [x] README improvements implemented

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
