### ISSUE TITLE
🚧Improve social preview & images

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#127]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the social preview image.

**Things To Do:**
1. by swapping out the logos with the project logo.  It cannot be a **_.svg_** file format.  
2. The logo should be centered horizontally and vertically.
3. The text _**KinsonDigital/Carbonate**_ should be changed to _**Carbonate**_.
4. Remove the badges at the bottom.

> **Note**
> This work can be done manually with paint dotnet and/or partially rebuilt using the social preview online tool.
> There are no code changes required for this issue. This means no PR is required as well.

Here is the list of files to help improve the preview image:
[various-images.zip](https://github.com/KinsonDigital/Carbonate/files/13379678/various-images.zip)

### Acceptance Criteria

```[tasklist]
### Social preview improved
- [x] Make sure that the node and line background pattern remains
- [x] The logo added should be centered horizontally
- [x] The logo added should be centered vertically between the top of the entire image and the top of the package text
- [x] The text _**KinsonDigital/Carbonate**_ has been changed to _**Carbonate**_
- [x] Badges removed
- [x] Images created for README updated
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
