### ISSUE TITLE
🚧Add fluent API

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#150]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a Fluent API to easily create subscriptions to reactables in combination with subscriptions to the same reactable.

This will require creating a Fluent API for each reactor type and the existing reactable.

Also, change the reactor ctor params for all receiver and responder `Action`s and `Func<T>`s to **NOT** be nullable.
> **Warning**
> This will have https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes.  The impact should be minimal because the reactors and responders become useless without setting the _**receiver**_ or _**responder**_ params.  This is the reason to make this change.  They should be required to be useful in the first place.

The fluent API should make setting the ID and receive/respond delegates required to be set before calling the final `Build()` method.  Do this by creating some interfaces to control the stage of creation.  Also, implement some fluent API methods that can be used to combine the required ID and receive/respond delegate params into a single method. This will give the user options.

Set up the Fluent API as a separate project.  This will give the ease in the future of possibly releasing the library as a NuGet package.

Create a NuGet package locally and set up a local NuGet package source to use for testing in **_Velaptor_**.  This means replacing some of the regular code and unit test code in _**Velaptor**_ to see how the Fluent API really works and possibly find issues.

### Acceptance Criteria

- [x] ~Fluent API created as a separate library project named `FluentCarbonate`~
- [x] Receive reactor Fluent APIs added
  - [x] Non-directional `ReceiveReactor` Fluent API created
      - [x] tests added
  - [x] Uni-Directional `ReceiveReactor<TDataIn>` Fluent API created
      - [x] tests added
- [x] Respond reactor Fluent APIs added
    - [x] Uni-directional `RespondReactor<TDataOut>` Fluent API created
      - [x] tests added
    - [x] Bi-directional `RespondReactor<TDataIn, TDataOut>` Fluent API created
      - [x] tests added
- [x] Uni-directional `PullReactable<TDataOut>` Fluent API created
    - [x] tests added
- [x] Uni-directional `PushReactable<TDataIn>` Fluent API created
    - [x] tests added
- [x] Bi-directional `PullReactable<TDataIn, TDataOut>` Fluent API created
    - [x] tests added
- [x] Non-directional `PushReactable` Fluent API created
    - [x] tests added
- [x] All new API types documented with XML comments
- [x] Receive and respond delegate params set to non-nullable
- [x] Velaptor testing performed for API compatibility
- [x] `.editorconfigs` updated
- [x] build status check workflow updated to build all solution projects
- [x] Update README examples
- [x] Moq code replaced with NSubstitute

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
The `.editorconfigs` did not need to be updated and were already the latest.

**Comment by CalvinWilkinson** [comment]
It was decided not to create the fluent API in a separate library project.  The Fluent API itself is very small and the extra work for another library is simply not worth the effort.  

If the need arises in the future, this can always be easily done later.
