### ISSUE TITLE
🚧Create extension methods

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#159]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create various extension methods that will use the fluent API to simplify the creation of subscriptions.
This will greatly reduce the code required for the majority of cases when subscribing to a reactable.

Create 2 versions for each `IReactable` type in the library.  One version will take a `name` param to give the user the ability to create their own name that they wish, and the other version is an overload without the `name` param and will automatically build a name based on which method and file invoked the extension method.

For auto naming, this will use the `[CallerMemberName]` and `[CallerFilePath]` attributes.

Extension method examples to implement shown below:
```cs
// Example 1: This is the version that takes an explicit name from the user
public static IDisposable CreateOneWayReceive<TData>(
    this IPushReactable<TData> reactable,
    Guid id,
    string name,
    Action<TData> action)
{
    var projOpenedSub = ISubscriptionBuilder.Create()
        .WithId(id)
        .WithName(name)
        .BuildOneWayReceive(action);

    return reactable.Subscribe(projOpenedSub);
}

// Example 2: This is the version that will auto-generate the name
public static IDisposable CreateOneWayReceive<TData>(
    this IPushReactable<TData> reactable,
    Guid id,
    Action<TData> action,
    [CallerMemberName] string callerMemberName = "",
    [CallerFilePath] string callerFilePath = "")
{
    callerMemberName = callerMemberName.Contains(".")
        ? callerMemberName.Split('.')[^1]
        : callerMemberName;

    var className = Path.GetFileNameWithoutExtension(callerFilePath);
    var callerName = $"{className}.{callerMemberName}";
    var subName = $"{callerName}() - {id}";

    var projOpenedSub = ISubscriptionBuilder.Create()
        .WithId(id)
        .WithName(subName)
        .BuildOneWayReceive(action);

    return reactable.Subscribe(projOpenedSub);
}
```

### **Purpose:**
The main reason is to simplify and reduce code for a better developer experience.  If higher control is needed by the user, this all still exists.  A common scenario is that the reactables get injected via a constructor, (if you are using dependency injection, 😉), and you require 3 or more different subscriptions to accomplish what you are doing.  Previously, without the fluent API, this was a ton of boilerplate code just to create all of the subscriptions.  Once the fluent API was released, this improved the situation, but this will be further improved for the common subscription scenarios when using the extension methods.

The new extension methods for all of the `IPushReactable<T>`'s will combine all of the usual steps for creating a subscription, into a more condensed version.  

Refer to 3 methods of subscription below:

**Version 1 (Without Fluent API):**
```cs
var subscription = new ReceiveSubscription<string>(
    id: Guid.NewGuid(),
    name: "my-subscription",
    onReceive: data => Console.WriteLine(data));

var unsubscriber = this.msgReactable.Subscribe(subscription);
```

**Version 2 (With Fluent API):**
```cs
var subscription = ISubscriptionBuilder.Create()
    .WithId(Guid.NewGuid())
    .WithName("my-subscription")
    .BuildOneWayReceive<string>(data => Console.WriteLine(data));

var unsubscriber = msgReactable.Subscribe(subscription);
```

**New Version 3 (With Extension Methods):**
```cs
var unsubscriber = msgReactable.CreateOneWayReceive(
    Guid.NewGuid(),
    data => Console.WriteLine(data));
```

**_Version 1_** was the original design of the API.  This approach gives you maximum control but with the downside of having to write more code and being more verbose.

**_Version 2_** was not as much about reducing code, but more about making the code more readable and guiding the user more into creating the subscription.

**_New Version 3_** will simplify things even more to not only maintain readability but also significantly reduce code.

As time moves on, the Fluent API will be expanded on as well as more extension methods to help make using the library as straightforward as possible, while also still giving users the ability to expand, extend, and have more control when needed.

### Acceptance Criteria

```[tasklist]
### Extenstion Methods For `Carbonate.NonDirectional.IPushReactable`
- [x] Method with name version created with clear XML docs created
- [x] Method with auto name version created clear XML docs created
```

```[tasklist]
### Extenstion Methods For `Carbonate.OneWay.IPushReactable<TIn>`
- [x] Method with name version created with clear XML docs created
- [x] Method with auto name version created clear XML docs created
```

```[tasklist]
### Extenstion Methods For `Carbonate.OneWay.IPullReactable<TOut>`
- [x] Method with name version created with clear XML docs created
- [x] Method with auto name version created clear XML docs created
```

```[tasklist]
### Extenstion Methods For `Carbonate.TwoWay.IPushPullReactable<TIn, TOut>`
- [x] Method with name version created with clear XML docs created
- [x] Method with auto name version created clear XML docs created
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
