### ISSUE TITLE
🚧Prevent unsubscription in OnRecieve

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#181]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Prevent an unsubscriber object from unusubscribing when its `Dispose()` method is called in an `OnReceieve()` call.

This can be prevented by invoking an exception.  This is because if a user unsubscribes inside of an `OnReceieve()` method call, this can cause issues due to processing each subscription at a time in the reactables.

To prevent this from being an issue, the for loops in the reactables all iterate the list of subscriptions from the end of the loop to the beginning so it does not try to access a subscription item that does not exist.

**Why is this?**
When a `SubscriptionUnsubscriber.Dispose()' method is called, it directly removes the subscription from the reactable's underlying array.  The `OnReceieve()` methods are invoked in an array.  This can cause a state of accessing an item that has been removed.

If we throw an exception from the unsubscriber, this will prevent users from trying to call the `Dispose()` method in the `OnReceieve()` call stack.

**How to prevent this?**
Internally, have the reactable communicate a state that the reactable is in the middle of processing notifications.  If this is the case, the `Dispose()` method of the unsubscriber should throw an exception.

1. Add a new parameter with the type `Func<bool>` and the name `isProcessing` to the `SubscriptionUnsubscriber` constructor.  The `bool` value will be the processing state that the reactable is currently in.  A value of `true` will mean that notifications are being processed and `false` means it is not.
> [!Note]
> The `ReactableBase` class will have a private method that returns a `bool` value that will be passed as the new ctor
> parameter of the `SubscriptionUnsubsciber' class.  The unsubscriber will then invoke this to check the processing
> state of the reactable that the subscription belongs to.
2. In the methods `Push` and `SendError` methods of the `PushReactable<TIn>` and `NonDirectional.PushReactable` classes, set the state to processing before the loops start and to not processing after the loops end.
3. Do the same thing for the `PushPullReactable<TIn, TOut>.PushPull` method.

Before the loop starts in the reactables, set the value of this property for each subscription

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] The `SubscriptionUnsubscriber` ctor has a new param of type `Func<bool>`
- [x] The name of the new ctor param is `isProcessing`
- [x] The loops in the `NonDirectional.PushReactable` class updated to set internal processing state
- [x] The loops in the `OneWay.PushReactable` class updated to set internal processing state
- [x] The loops in the `PushReactable<TIn>` class updated to set the internal processing state
- [x] The loops in the `PushPullReactable<TIn, TOut>` class updated to set the internal processing state
- [x] The `Dispose()` method in the `SubscriptionUnsubscriber` class throws an exception if the reactables are currently processing
```

### ToDo Items

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
