### ISSUE TITLE
🚧Improve and update sonar scan status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#184]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the sonar scan status check to use the sonar cloud GitHub action.

**Resources:**
- [SonarCloud Scan GitHub Action](https://github.com/marketplace/actions/sonarcloud-scan)

Make sure to use the `pull_request` workflow trigger and do manual testing by setting the default branch to the this issues' feature branch.  This is to make sure that the changes work properly.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] 'sonar-scan-pr-status-check.yml' workflow updated
- [x] Manual testing performed
- [x] Repo default branch set back to 'preview'
```

### ToDo Items

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
