### ISSUE TITLE
🚧Fix bug with unsubscriptions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#20]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug where unsubscribing from an event only unsubscribed from half of the total events.

This is occurring because the loop starts from 0 and iterates to the end of the loop.  But the problem is when a reactor is unsubscribed, it removes itself from the subscription list, which indirectly reduces the number of total subscriptions.  This ends up indirectly moving closer to the end of the list.  This has the behavior of reaching the end of the subscription list with only half of the iterations.

**How to Fix:**
Loop through the subscription list starting from the end and moving to the first item instead.

Create unit tests to verify that this is going on

### Acceptance Criteria

- [x] Unsubscription bug fixed.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
