### ISSUE TITLE
🚧Fix bug with null ref exceptions on unsubscribe all

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#202]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug where the `UnsubscribeAll()` method throws a null reference exception in the `ReactableBase` class.

This is occurring due to the list of subscriptions becoming null during unsubscription.  Depending how the implementations of the various subscription delegates are working, the subscription can become null.  As the loop processes through the collection of subscriptions to unsubscribe, it runs into a null subscription and the exception is thrown.

> [!Note]
> Before completing this pull request, create a local nuget package for Velaptor to consume and 
> test this out to make sure everything is working correctly.
> Velaptor is going through an upgrade with Carbonate v1.0.0-preview.17 and is running into issues.
> The issue related to this upgrade is:
> - KinsonDigital/Velaptor#931

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [ ] Bug has been fixed
- [ ] Proper testing performed in Velaptor
- [ ] create pr powershell script added to project
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
