### ISSUE TITLE
🚧Fix broken logo link for nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#28]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

The logo URL in the README is not working on nuget.org in the NuGet package.  This is due to the domain being incorrect.

The URL is a relative file path but needs to be an actual URL with an approved domain.  Use the URL below:

```txt
![carbonate-logo](https://raw.githubusercontent.com/KinsonDigital/Carbonate/release/v1.0.0/Documentation/Images/carbonate-logo-light-mode.png)
```

**Fix Location In README:**
```diff
- ![logo](./Documentation/Images/carbonate-logo-light-mode.png#gh-light-mode-only)
+ ![carbonate-logo](https://raw.githubusercontent.com/KinsonDigital/Carbonate/release/v1.0.0/Documentation/Images/carbonate-logo-light-mode.png)
```

### Acceptance Criteria

- [ ] Logo fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
