### ISSUE TITLE
🚧Fix issue with Reactable disposal process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#40]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug with the disposal process of the `Reactable` class.  The error was caught in the _**Velaptor**_ project.

**Error:**
```txt
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at Carbonate.Reactable.Dispose(Boolean disposing)
   at Carbonate.Reactable.Dispose()
   at Velaptor.OpenGL.GLWindow.Dispose(Boolean disposing) in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Velaptor\OpenGL\GLWindow.cs:line 575
   at Velaptor.OpenGL.GLWindow.Dispose() in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Velaptor\OpenGL\GLWindow.cs:line 272
   at Velaptor.UI.Window.Dispose(Boolean disposing) in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Velaptor\UI\Window.cs:line 212
   at Velaptor.UI.Window.Dispose() in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Velaptor\UI\Window.cs:line 152
   at VelaptorTesting.Program.<>c.<Main>b__2_1() in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Testing\VelaptorTesting\Program.cs:line 95
   at Velaptor.OpenGL.GLWindow.GLWindow_Closing() in K:\SOFTWARE-DEV\PERSONAL\Velaptor\Velaptor\OpenGL\GLWindow.cs:line 393
   at Silk.NET.Windowing.Glfw.GlfwWindow.<RegisterCallbacks>b__86_3(WindowHandle* window)
```

1.  In the `private` method `Reactable.Dispose(bool)`, instead of looping through all of the GUIDS and unsubscribing each one, just call the `UnsubscribeAll()` method.
2. Add additional code docs to the `Reactable.Dispose()` method by adding a `/// <remarks/>` section explaining that all subscriptions are completed and unsubscribed.
3. Add an `isDisposed` check for each method and if disposed, throws an `ObjectDisposedException`.

### Acceptance Criteria

- [x] Disposal error fixed
- [x] Each `Reactable` method checks for disposal and throws an exception if disposed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
