### ISSUE TITLE
🚧Fix unsubscription bug

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#41]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug where if any of the `Reactor` action implementations unsubscribe from a `Reactable`, an exception is thrown with array index access.

This is occurring because the disposal of a reactor removes the reactor from the internal `Reactor` subscription items.  This is because the element iteration is calling `Reactor` action implementations in the same call stack so when the callstack is unwinding to reference the next item, the item has already been removed.

This should be an easy fix.  For all of the for loops in the `Reactable` class, perform a check to validate if the next `int` index to be used even exists first before trying to call the next `Reactor` action method.

> **Note**
> First create a unit or integration test to duplicate the issue before solving it.

> **https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%90%9Bbug 's fixed:**
> - `Reactable.Unsubscribe()` was not removing the subscription from the internal list
> - `Reactable.Push()` fixed premature unsubscription issues from `OnNext()` implementations
> - `Reactable.UnsubscribeAll()` fixed premature unsubscription issues from `OnComplete()` implementations

> **https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes 's**
> - `ISerialize` interface renamed to `ISerializerService`

### Acceptance Criteria

- [x] Tests created to duplicate the issue
- [x] Issue fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
