### ISSUE TITLE
🚧Change message and result generics

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#59]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Move the generic to the `IResult` and `IMessage` interfaces.

> **Example**
Currently, you cannot return a `struct` type.  This is due to the generic constraint on the `IResult.GetValue<T>()` method.
This change is moving the generic constraint from the method to the entire interface.

### **Reason:**
This will give the ability to user to control the kind of data that the interfaces deals with in a predictable type-safe manner.
These changes are required to open up for more control requirements for **_Velaptor_**.

>**Warning**
This is going to contain several breaking changes.  This is occurring due to the use of the library in the _**Velaptor**_ project, which is used to dictate the direction, and features, and to find bugs in the library.

### Acceptance Criteria

- [x] Generic type on the `IResult.GetValue<T>()` method moved to the `interface` level
- [x] All other interfaces are updated accordingly to adjust for type change.
- [x] Generic type on the `IMessage.GetData<T>()` method moved to the `interface` level
- [x] All other interfaces are updated accordingly to adjust for type change.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes
The `Responder` interface, (changed to `Responder<TResult>`), does not return a nullable `IResult` (changed to`IResult<TResult>`) anymore.

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes
Moved the generic in the `IResult` interface from the `GetValue()` method to the interface level.

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes
Moved the generic in the `IMessage` interface from the `GetData()` method to the interface level.

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/Carbonate/labels/%F0%9F%A7%A8breaking%20changes
Removed the `IPushable<T>.PushData<T>()` method.
Removed the `PushReactable.PushData<T>()` method.

**Comment by CalvinWilkinson** [comment]
The original PR #61 was merged into the incorrect branch.  It was merged into **_v1.0.0-preview.11_** instead of **_v1.0.0-preview.12_**.

Another PR #64 was created to merge the content into the correct branch.  Another was created because the original PR was already merged.  The original PR was reverted to keep the preview feature branch _**v1.0.0-preview.11**_ in the correct state.
