### ISSUE TITLE
🚧Remove sealed from the reactable classes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#60]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the `sealed` keyword from the `PushReactable` and `PullReactable` classes.

This will allow more control for the user over the kind of data that can be used with the reactables.
An example would be high-performance scenarios.

Change the following `PullReactable` class methods to virtual:
- `Pull(Guid)`
- `Pull(IMessage, Guid)` 

Change the following `PushReactable` class methods to virtual:
- `Push()`
- `PushData(Guid)`
- `PushMessage(IMessage, Guid)` 

### Acceptance Criteria

- [ ] Changes made to `PushReactable` class
    - [ ] Class set to `sealed`
    - [ ] `Push()` set to virtual
    - [ ] `PushData(Guid)` set to virtual
    - [ ] `PushMessage(IMessage, Guid)`  set to virtual

- [ ] Changes made to `PullReactable` class
    - [ ] Class set to `sealed`
    - [ ] `Pull(Guid)` set to virtual
    - [ ] `Pull(IMessage, Guid)`  set to virtual

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- #59 

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Result:** Implemented in the issue below:

- #59
