### ISSUE TITLE
🚧Improve message factory

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#68]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the `MessageFactory` class.

1. Rename the `MessageFactory` class to `JsonMessageFactory`
2. Change the class from `static` to `public sealed`
3. Create an interface for the class.
    > **Note** This will improve testability and give users the ability to create there own implementations.

### Acceptance Criteria

- [ ] The class `MessageFactory` is renamed to `JsonMessageFactory`
- [ ] The class is changed from `static` to `public sealed`
- [ ] Interface for the class created
    - [ ] Code refactored to use the interface

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation.

**Reason:**
This is not required anymore due to the removal of the factory classes with issue #71
