### ISSUE TITLE
🚧Add memory specific API for perf

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#69]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the required API to allow the pushing and pulling of data of type `Memory<T>`. 
This requires creating an API version for `IPullReactable<TDataOut>`, `IPullReactable<TDataIn, TDataOut>`, and `IPushReactable<TDataIn>` scenarios.

### **Reason:**
This can be used for high performance scenarios when there is a need to push and pull contiguous data around.

### Acceptance Criteria

- [ ] `Memory<T>` versions of all the required interfaces and classes created.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:** Not needed anymore
