### ISSUE TITLE
🚧Remove IMessage and IResult

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#71]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the `IMessage` and `IResult` interfaces an all related implementations and code.

### **Reason:**
These types are not required/needed anymore due to the changes that have occurred in the library.  This was required in the beginning when the library was much smaller and there was only a single reactable that push all kinds of data.  Now that the library uses generics and gives more control to the user, these are not needed anymore.

### Acceptance Criteria

- [x] The `IMessage` interface removed
    - [x] All associated implementations and code removed
- [x] The `IResult` interface removed
    - [x] All associated implementations and code removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
