### ISSUE TITLE
🚧Un-seal various types

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#77]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Change various classes from `sealed` to not `sealed`.

**Reason:**
This is to allow users to inherit from the classes to give them control.
Example: custom types can be created to simplify dealing with generics as well as not having to re-implement the functionality provided by the types over and over again.

Also set the `OnReceive()` and `OnResponse()` methods to virtual.

Change the classes below:
    - `UniDirectional.ReceiveReactor`
    - `UniDirectional.RespondReactor`
    - `NonDirectional.ReceiveReactor`
    - `BiDirectional.RespondReactor`

### Acceptance Criteria

- [x] `UniDirectional.ReceiveReactor` change to non-sealed
    - [x] `sealed` keyword removed
    - [x] `OnReceive()` method set to virtual
- [x] `UniDirectional.RespondReactor` change to non-sealed
    - [x] `sealed` keyword removed
    - [x] `OnRespond()` method set to virtual
- [x] `NonDirectional.ReceiveReactor` change to non-sealed
    - [x] `sealed` keyword removed
    - [x] `OnReceive()` method set to virtual
- [x] `BiDirectional.RespondReactor` change to non-sealed
    - [x] `sealed` keyword removed
    - [x] `OnRespond()` method set to virtual

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
