### ISSUE TITLE
🚧Add parameterless constructor to Reactable

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#9]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a parameterless constructor to the `Reactable` class.

**Reason:**
This parameterless constructor will create its own serializer for the default JSON serializer.  The code base already has an `internal` implementation of `ISerializer` that can be used.  The intent is to hide this default serializer from the user so that when using default messaging, the user does not have to worry about dealing with serialization.  Of course, they can provide their own implementation if they want to.

To pull this off, create an instance of the `internal` `JsonSerializer` class.  Add the `[ExcludeFromCodeCoverage]` attribute on this constructor as we.

### Acceptance Criteria

- [x] Parameterless constructor added to the `Reactable` class.
    - [x] Create an instance of `JsonSerializer` and set to a private class field
    - [x] `[ExcludeFromCodeCoverage]` attribute added to the constructor

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
