### ISSUE TITLE
🚧Update Readme

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Carbonate#90]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes making sure all sections are in this order:

1. Logo
2. Repo Name
3. Badges
4. Notice
5. About
6. Features - (to be done at a later date by Calvin)
7. Add Demo (to be done at a later date by Calvin)
8. Contributing
9. Maintainers
10. License

**Contributing**
Use wording from Velaptor

Use Maintainers, Contributing and License section from Velaptor
Remove Practices section
Remove Further Resources section
Use emoji's like in Velaptor for each section
Double check spelling/grammar
Verify all links work and point correctly

### Acceptance Criteria
Sections are in this order:
- [x] Logo
- [x] Repo Name
- [x] Badges
- [x] Notice
- [x] About
- [x] Contributing is like Velaptor
- [x] Maintainers is like Velaptor
- [x] License is like Velaptor
- [x]  Emoji's are like Velaptor for each section
- [x]  Spelling/grammar checked
- [x]  All links work and point correctly

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
