### ISSUE TITLE
🚧Remove the contributing document

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Carbonate#96]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the _**CONTRIBUTING.md**_ document from the root of the repository.
Also update the link to the document in the contribution section of the _**README.md**_ file.

**README link change:**
```diff
- To learn how to contribute to the project, go [here](https://github.com/KinsonDigital/Carbonate/blob/release/v1.0.0/CONTRIBUTING.md).
+ To learn how to contribute to the project, go [here](https://raw.githubusercontent.com/KinsonDigital/.github/master/docs/CONTRIBUTING.md).
```

### Acceptance Criteria

- [x] The _**CONTRIBUTING.md**_ document removed.
- [x] The _**README.md**_ file link updated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
